builders:
  dart_to_dill:
    import: "package:build_aot/build_aot.dart"
    builder_factories:
      - dillBuilder
      - dillToCBuilder
    build_extensions:
      .dart:
        - .dill
        - .dill.txt
    auto_apply: root_package