name: build_aot
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  build: ^1.0.0
  build_config: ^0.3.0
  build_vm_compilers: ^0.1.1
  code_buffer: ^1.0.0
  scratch_space: ^0.0.3
dev_dependencies: 
  build_runner: ^1.0.0
